//go:build cgo && arm64

// ARM NEON (AArch64 Advanced SIMD) pack/unpack kernels for the FOR-delta v6
// block codec, called from blockpack_arm64.go and compiled by cgo as part of
// the index package. Mirrors the coverage of the AVX2 path in
// blockpack_cgo.go: unpack for bits ∈ {4, 8, 16, 24}, pack for bits ∈
// {4, 8, 16}. Every function handles exactly 128 values (BlockSize).
//
// The wire format is not implementation-defined: it must match
// packBits32/unpackBits32 in blockpack.go exactly (little-endian bit stream,
// values packed low-to-high in insertion order), the same format the pure-Go
// and AVX2 paths produce and consume. blockpack_neon_test.go checks these
// kernels against golden vectors generated by that Go implementation.
//
// NEON is part of the mandatory AArch64 baseline, so no runtime feature
// check is needed (unlike AVX2 on x86-64).

#include <arm_neon.h>

#include <cstdint>
#include <cstring>

extern "C" {

// Zero-extends 128 packed uint8 values to uint32, 8 lanes per iteration.
// src: 128 bytes; out: 128 uint32.
void unpack8_neon(const uint8_t *src, uint32_t *out) {
    for (int i = 0; i < 128; i += 8) {
        const uint16x8_t w = vmovl_u8(vld1_u8(src + i));
        vst1q_u32(out + i, vmovl_u16(vget_low_u16(w)));
        vst1q_u32(out + i + 4, vmovl_high_u16(w));
    }
}

// Zero-extends 128 packed uint16 values (little-endian) to uint32.
// src: 128 uint16 (may be unaligned); out: 128 uint32.
void unpack16_neon(const uint16_t *src, uint32_t *out) {
    for (int i = 0; i < 128; i += 8) {
        const uint16x8_t half = vld1q_u16(src + i);
        vst1q_u32(out + i, vmovl_u16(vget_low_u16(half)));
        vst1q_u32(out + i + 4, vmovl_high_u16(half));
    }
}

// Unpacks 128 packed 4-bit values to uint32. Each source byte holds two
// values: low nibble = even index, high nibble = odd index.
// src: 64 bytes; out: 128 uint32.
void unpack4_neon(const uint8_t *src, uint32_t *out) {
    const uint8x8_t lo_mask = vdup_n_u8(0x0F);
    for (int i = 0, o = 0; i < 64; i += 8, o += 16) {
        const uint8x8_t v = vld1_u8(src + i);
        const uint8x8_t lo = vand_u8(v, lo_mask);
        const uint8x8_t hi = vshr_n_u8(v, 4);
        // Interleave to [lo0,hi0,lo1,hi1,...]: values o..o+7, then o+8..o+15.
        const uint16x8_t w1 = vmovl_u8(vzip1_u8(lo, hi));
        const uint16x8_t w2 = vmovl_u8(vzip2_u8(lo, hi));
        vst1q_u32(out + o, vmovl_u16(vget_low_u16(w1)));
        vst1q_u32(out + o + 4, vmovl_high_u16(w1));
        vst1q_u32(out + o + 8, vmovl_u16(vget_low_u16(w2)));
        vst1q_u32(out + o + 12, vmovl_high_u16(w2));
    }
}

// Unpacks 128 packed 3-byte (24-bit) little-endian values to uint32. The
// first 124 values use a table lookup that spreads each 3-byte group into a
// 4-byte lane (index 255 → zero byte); the last 4 are scalar, matching
// unpack24_avx2's split. The 16-byte loads read up to 4 bytes past the 12
// they need, but never past byte 384 of src.
// src: 384 bytes; out: 128 uint32.
void unpack24_neon(const uint8_t *src, uint32_t *out) {
    static const uint8_t idx[16] = {0, 1, 2, 255, 3, 4, 5, 255,
                                    6, 7, 8, 255, 9, 10, 11, 255};
    const uint8x16_t table = vld1q_u8(idx);
    int i = 0;
    for (; i < 124; i += 4) {
        const uint8x16_t raw = vld1q_u8(src + i * 3);
        vst1q_u32(out + i, vreinterpretq_u32_u8(vqtbl1q_u8(raw, table)));
    }
    for (; i < 128; ++i) {
        const uint8_t *p = src + i * 3;
        out[i] = uint32_t(p[0]) | (uint32_t(p[1]) << 8) | (uint32_t(p[2]) << 16);
    }
}

// Narrows 128 uint32 values (each < 256) to 128 packed bytes.
// src: 128 uint32; dst: 128 bytes.
void pack8_neon(const uint32_t *src, uint8_t *dst) {
    for (int i = 0; i < 128; i += 8) {
        const uint16x8_t ab16 = vcombine_u16(vqmovn_u32(vld1q_u32(src + i)),
                                             vqmovn_u32(vld1q_u32(src + i + 4)));
        vst1_u8(dst + i, vqmovn_u16(ab16));
    }
}

// Narrows 128 uint32 values (each < 65536) to 128 packed little-endian uint16.
// src: 128 uint32; dst: 128 uint16 (may be unaligned).
void pack16_neon(const uint32_t *src, uint16_t *dst) {
    for (int i = 0; i < 128; i += 8) {
        vst1q_u16(dst + i, vcombine_u16(vqmovn_u32(vld1q_u32(src + i)),
                                        vqmovn_u32(vld1q_u32(src + i + 4))));
    }
}

// Packs 128 uint32 values (each < 16) into 64 bytes:
// dst[k] = src[2k] | (src[2k+1] << 4).
// src: 128 uint32; dst: 64 bytes.
void pack4_neon(const uint32_t *src, uint8_t *dst) {
    for (int i = 0, o = 0; i < 128; i += 8, o += 4) {
        const uint16x8_t ab16 = vcombine_u16(vqmovn_u32(vld1q_u32(src + i)),
                                             vqmovn_u32(vld1q_u32(src + i + 4)));
        const uint8x8_t v8 = vqmovn_u16(ab16);  // 8 nibble values v0..v7
        const uint8x8_t even = vuzp1_u8(v8, v8);  // v0,v2,v4,v6,...
        const uint8x8_t odd = vuzp2_u8(v8, v8);   // v1,v3,v5,v7,...
        const uint8x8_t packed = vorr_u8(even, vshl_n_u8(odd, 4));
        // Store the low 4 bytes. memcpy rather than a uint32_t* store: dst
        // is a byte buffer, so the cast would violate strict aliasing.
        const uint32_t word = vget_lane_u32(vreinterpret_u32_u8(packed), 0);
        std::memcpy(dst + o, &word, sizeof word);
    }
}

}  // extern "C"
