// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: internal/replication/replication.proto

package replication

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WALReplication_StreamWAL_FullMethodName = "/replication.WALReplication/StreamWAL"
)

// WALReplicationClient is the client API for WALReplication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WALReplication streams WAL entries from primary to replicas.
type WALReplicationClient interface {
	StreamWAL(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WALEntry], error)
}

type wALReplicationClient struct {
	cc grpc.ClientConnInterface
}

func NewWALReplicationClient(cc grpc.ClientConnInterface) WALReplicationClient {
	return &wALReplicationClient{cc}
}

func (c *wALReplicationClient) StreamWAL(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WALEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WALReplication_ServiceDesc.Streams[0], WALReplication_StreamWAL_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, WALEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WALReplication_StreamWALClient = grpc.ServerStreamingClient[WALEntry]

// WALReplicationServer is the server API for WALReplication service.
// All implementations must embed UnimplementedWALReplicationServer
// for forward compatibility.
//
// WALReplication streams WAL entries from primary to replicas.
type WALReplicationServer interface {
	StreamWAL(*StreamRequest, grpc.ServerStreamingServer[WALEntry]) error
	mustEmbedUnimplementedWALReplicationServer()
}

// UnimplementedWALReplicationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWALReplicationServer struct{}

func (UnimplementedWALReplicationServer) StreamWAL(*StreamRequest, grpc.ServerStreamingServer[WALEntry]) error {
	return status.Error(codes.Unimplemented, "method StreamWAL not implemented")
}
func (UnimplementedWALReplicationServer) mustEmbedUnimplementedWALReplicationServer() {}
func (UnimplementedWALReplicationServer) testEmbeddedByValue()                        {}

// UnsafeWALReplicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WALReplicationServer will
// result in compilation errors.
type UnsafeWALReplicationServer interface {
	mustEmbedUnimplementedWALReplicationServer()
}

func RegisterWALReplicationServer(s grpc.ServiceRegistrar, srv WALReplicationServer) {
	// If the following call panics, it indicates UnimplementedWALReplicationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WALReplication_ServiceDesc, srv)
}

func _WALReplication_StreamWAL_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WALReplicationServer).StreamWAL(m, &grpc.GenericServerStream[StreamRequest, WALEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WALReplication_StreamWALServer = grpc.ServerStreamingServer[WALEntry]

// WALReplication_ServiceDesc is the grpc.ServiceDesc for WALReplication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WALReplication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "replication.WALReplication",
	HandlerType: (*WALReplicationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamWAL",
			Handler:       _WALReplication_StreamWAL_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/replication/replication.proto",
}
