// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/replication/replication.proto

package replication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamRequest carries the replica's highest applied sequence number.
// The primary will stream all entries with seq > from_seq.
type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	FromSeq       uint64                 `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_internal_replication_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_replication_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_internal_replication_replication_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *StreamRequest) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

// WALEntry mirrors the NDJSON WAL format.
type WALEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Op            string                 `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"` // "index" | "delete"
	DocId         string                 `protobuf:"bytes,3,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TsUnix        int64                  `protobuf:"varint,6,opt,name=ts_unix,json=tsUnix,proto3" json:"ts_unix,omitempty"` // Unix nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALEntry) Reset() {
	*x = WALEntry{}
	mi := &file_internal_replication_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALEntry) ProtoMessage() {}

func (x *WALEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_replication_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALEntry.ProtoReflect.Descriptor instead.
func (*WALEntry) Descriptor() ([]byte, []int) {
	return file_internal_replication_replication_proto_rawDescGZIP(), []int{1}
}

func (x *WALEntry) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *WALEntry) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *WALEntry) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *WALEntry) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *WALEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WALEntry) GetTsUnix() int64 {
	if x != nil {
		return x.TsUnix
	}
	return 0
}

var File_internal_replication_replication_proto protoreflect.FileDescriptor

const file_internal_replication_replication_proto_rawDesc = "" +
	"\n" +
	"&internal/replication/replication.proto\x12\vreplication\"E\n" +
	"\rStreamRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x04R\afromSeq\"\xee\x01\n" +
	"\bWALEntry\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\tR\x02op\x12\x15\n" +
	"\x06doc_id\x18\x03 \x01(\tR\x05docId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12?\n" +
	"\bmetadata\x18\x05 \x03(\v2#.replication.WALEntry.MetadataEntryR\bmetadata\x12\x17\n" +
	"\ats_unix\x18\x06 \x01(\x03R\x06tsUnix\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012R\n" +
	"\x0eWALReplication\x12@\n" +
	"\tStreamWAL\x12\x1a.replication.StreamRequest\x1a\x15.replication.WALEntry0\x01B+Z)search-eval-platform/internal/replicationb\x06proto3"

var (
	file_internal_replication_replication_proto_rawDescOnce sync.Once
	file_internal_replication_replication_proto_rawDescData []byte
)

func file_internal_replication_replication_proto_rawDescGZIP() []byte {
	file_internal_replication_replication_proto_rawDescOnce.Do(func() {
		file_internal_replication_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_replication_replication_proto_rawDesc), len(file_internal_replication_replication_proto_rawDesc)))
	})
	return file_internal_replication_replication_proto_rawDescData
}

var file_internal_replication_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_replication_replication_proto_goTypes = []any{
	(*StreamRequest)(nil), // 0: replication.StreamRequest
	(*WALEntry)(nil),      // 1: replication.WALEntry
	nil,                   // 2: replication.WALEntry.MetadataEntry
}
var file_internal_replication_replication_proto_depIdxs = []int32{
	2, // 0: replication.WALEntry.metadata:type_name -> replication.WALEntry.MetadataEntry
	0, // 1: replication.WALReplication.StreamWAL:input_type -> replication.StreamRequest
	1, // 2: replication.WALReplication.StreamWAL:output_type -> replication.WALEntry
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_replication_replication_proto_init() }
func file_internal_replication_replication_proto_init() {
	if File_internal_replication_replication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_replication_replication_proto_rawDesc), len(file_internal_replication_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_replication_replication_proto_goTypes,
		DependencyIndexes: file_internal_replication_replication_proto_depIdxs,
		MessageInfos:      file_internal_replication_replication_proto_msgTypes,
	}.Build()
	File_internal_replication_replication_proto = out.File
	file_internal_replication_replication_proto_goTypes = nil
	file_internal_replication_replication_proto_depIdxs = nil
}
